In [ ]:
'''
2025년 9월 23일 화요일 화이팅입니다~

어느새 이론 강의도 막바지에 접어들어 26강입니다!
목표는 이번 주 내로 이론강의를 떼고 
시험 예제풀이로 접어들며
이론강의 부분을 회독하며 내 것으로 만드는 작업에 들어가고 싶습니다.

제발~~
'''

## 딥러닝 기본 - 텐서플로우 실습

#### 1. Tensor

In [ ]:
'''
Tensor는 딥러닝 프레임워크에서 
데이터를 표현하고 처리하기 위한 다차원 배열구조이다

차원에 따라 스칼라(0차원), 벡터(1차원), 매트릭스(2차원) 등등으로 발전하며,
딥러닝에서 데이터를 다루는 기본 단위이다.
'''

In [1]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\16z90p\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (1.75.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\16z90p\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\16z90p\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\16z90p\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\16z90p\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\16z90p\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\16z90p\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\16z90p\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\16z90p\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\16z90p\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\16z90p\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\16z90p\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\16z90p\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\16z90p\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\16z90p\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)

In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [4]:
# 학습 데이터 정의 - y = 3x + 5의 그래프

x = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

y = np.array([[8], [11], [14], [17], [20], [23], [26], [29], [32], [35]])

In [7]:
# Sequential 모델 정의
model = Sequential()

# Dense 층 추가
model.add(Dense(
    units=1,                # 출력층 뉴런 수 (회귀 문제니까 출력이 하나)
    activation='linear',    # 활성화 함수  ('relu', 'sigmoid', 'tanh'등의 옵션 가능)
    input_shape=[1],        # 입력 데이터 형태 (1차원인 x값을 학습시킴)
    kernel_initializer=tf.keras.initializers.GlorotUniform(seed=55),    # GlorotUniform 초기화 (가중치 랜덤초기화)
))

model.summary()     # 만들어진 모델에 대한 요약

c:\Users\16Z90P\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
# 모델 컴파일
model.compile(
    optimizer= 'sgd',               # 옵티마이져(학습 알고리즘) : SGD
    loss= 'mean_squared_error',     # 손실함수 : 평균제곱오차
    metrics=['mae']                 # 추가 매트릭(손실함수 외 성능지표) : 평균 절대오차
)

In [ ]:
# 모델 학습 - 머신러닝 때와 동일함
model.fit(x, y, epochs=200)

In [11]:
model.weights

[<Variable path=sequential/dense/kernel, shape=(1, 1), dtype=float32, value=[[3.1816113]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[3.735655]>]

In [13]:
weights, biases = model.layers[0].get_weights()

print(f'가중치:{weights}')
print(f'바이어스:{biases}')

가중치:[[3.1816113]]
바이어스:[3.735655]

In [14]:
# 예측할 데이터
new_data = np.array(([12],[14],[16],[18],[20]))

# 예측
prediction = model.predict(new_data)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
[[41.914993]
 [48.278214]
 [54.641438]
 [61.00466 ]
 [67.36788 ]]

In [ ]:
help(model.fit)

#### 2. TensorFlow 설치 및 실습

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('datasets/CVD_cleaned.csv')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308854 entries, 0 to 308853
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   General_Health                308854 non-null  object
 1   Checkup                       308854 non-null  object
 2   Exercise                      308854 non-null  object
 3   Heart_Disease                 308854 non-null  object
 4   Skin_Cancer                   308854 non-null  object
 5   Other_Cancer                  308854 non-null  object
 6   Depression                    308854 non-null  object
 7   Diabetes                      308854 non-null  object
 8   Arthritis                     308854 non-null  object
 9   Sex                           308854 non-null  object
 10  Age_Category                  308854 non-null  object
 11  Height_(cm)                   308854 non-null  float64
 12  Weight_(kg)                   308854 non-null  float64
 13  BMI                           308854 non-null  float64
 14  Smoking_History               308854 non-null  object
 15  Alcohol_Consumption           308854 non-null  float64
 16  Fruit_Consumption             308854 non-null  float64
 17  Green_Vegetables_Consumption  308854 non-null  float64
 18  FriedPotato_Consumption       308854 non-null  float64
dtypes: float64(7), object(12)
memory usage: 44.8+ MB

## 각 데이터 컬럼 설명

| 컬럼명                         | 설명                        | 비고                                                                 |
|------------------------------|-----------------------------|----------------------------------------------------------------------|
| General_Health               | 일반적인 건강 상태           | Poor : 매우 나쁨<br>Fair : 나쁨<br>Good : 보통<br>Very Good : 좋음<br>Excellent : 매우 좋음 |
| Checkup                      | 건강 검진 여부               | Within the past year : 1년 이내<br>Within the past 2 years : 2년 이내<br>Within the past 5 years : 5년 이내<br>5 or more years ago : 5년 이상 또는 그이상<br>Never : 한적 없음 |
| Exercise                     | 지난 한달동안 정기적인 운동 여부 | No : 아니요<br>Yes : 예                                            |
| Heart_Disease                | 심혈관 질환 여부              | No : 아니요<br>Yes : 예                                             |
| Skin_Cancer                  | 피부암 여부                  | No : 아니요<br>Yes : 예                                             |
| Other_Cancer                 | 기타 암 발생 여부            | No : 아니요<br>Yes : 예                                             |
| Depression                   | 우울증 여부                  | No : 아니요<br>Yes : 예                                             |
| Diabetes                     | 당뇨병 여부                  | No : 아니요<br>Yes : 예<br>No, pre-diabetes or borderline diabetes : 당뇨 전단계 또는 경계성 당뇨병 상태 <br>Yes, but female told only during pregnancy : 임신 중에만 당뇨병 진단을 받은 여성 |
| Arthritis                    | 관절염 여부                  | No : 아니요<br>Yes : 예                                             |
| sex                          | 응답자 성별                  | Male : 남자<br>Female : 여자                                       |
| Age_Category                 | 연령대별 구분(5 기준)        | 18 ~ 80세 이상까지 총 13개의 카테고리                                                                     |
| Height_(cm)                  | 응답자 신장                  |                                                                      |
| Weight_(kg)                  | 응답자 체중                  |                                                                      |
| BMI                          | 응답자 체질량 지수           |                                                                      |
| Smoking_History              | 흡연 여부                    | No : 아니요<br>Yes : 예                                             |
| Alcohol_Consumption          | 알코올 소비                  |                                                                      |
| Fruit_Consumption            | 과일 소비                    |                                                                      |
| Green_Vegetables_Consumption | 녹색 야채 소비               |                                                                      |
| FriedPotato_Consumption      | 감자 튀김 소비               |                                                                      |

In [4]:
data.head()

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0

In [5]:
data.describe()

,Height_(cm),Weight_(kg),BMI,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
count,308854.000000,308854.000000,308854.000000,308854.000000,308854.000000,308854.000000,308854.000000
mean,170.615249,83.588655,28.626211,5.096366,29.835200,15.110441,6.296616
std,10.658026,21.343210,6.522323,8.199763,24.875735,14.926238,8.582954
min,91.000000,24.950000,12.020000,0.000000,0.000000,0.000000,0.000000
25%,163.000000,68.040000,24.210000,0.000000,12.000000,4.000000,2.000000
50%,170.000000,81.650000,27.440000,1.000000,30.000000,12.000000,4.000000
75%,178.000000,95.250000,31.850000,6.000000,30.000000,20.000000,8.000000
max,241.000000,293.020000,99.330000,30.000000,120.000000,128.000000,128.000000

In [7]:
# 결측치 확인
data.isna().sum()

General_Health                  0
Checkup                         0
Exercise                        0
Heart_Disease                   0
Skin_Cancer                     0
Other_Cancer                    0
Depression                      0
Diabetes                        0
Arthritis                       0
Sex                             0
Age_Category                    0
Height_(cm)                     0
Weight_(kg)                     0
BMI                             0
Smoking_History                 0
Alcohol_Consumption             0
Fruit_Consumption               0
Green_Vegetables_Consumption    0
FriedPotato_Consumption         0
dtype: int64

In [ ]:
# 범주형 데이터 원-핫 인코딩

# 대상 컬럼 리스트 (범주형)
one_hot_columns = [
    'General_Health', 'Checkup', 'Diabetes', 'Exercise',
    'Skin_Cancer', 'Other_Cancer', 'Age_Category',
    'Depression', 'Arthritis', 'Sex', 'Smoking_History'
]

# 원핫 인코딩 진행
data = pd.get_dummies(data, columns=one_hot_columns, drop_first=True)   # drop_first 는 이지선다에서 칼럼을 두개 만들지 않도록 (다중공선성)

data.head()

# 독립변수에 원핫인코딩을 적용하는 이유는 - True/False 로 나오기 때문에 절대적인 크기 자체를 가지지 않아 잘못된 학습이 되지 않게 하기 위함임

,Heart_Disease,Height_(cm),Weight_(kg),BMI,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption,General_Health_Fair,General_Health_Good,...,Age_Category_55-59,Age_Category_60-64,Age_Category_65-69,Age_Category_70-74,Age_Category_75-79,Age_Category_80+,Depression_Yes,Arthritis_Yes,Sex_Male,Smoking_History_Yes
0,No,150.0,32.66,14.54,0.0,30.0,16.0,12.0,False,False,...,False,False,False,True,False,False,False,True,False,True
1,Yes,165.0,77.11,28.29,0.0,30.0,0.0,4.0,False,False,...,False,False,False,True,False,False,False,False,False,False
2,No,163.0,88.45,33.47,4.0,12.0,3.0,16.0,False,False,...,False,True,False,False,False,False,False,False,False,False
3,Yes,180.0,93.44,28.73,0.0,30.0,30.0,8.0,False,False,...,False,False,False,False,True,False,False,False,True,False
4,No,191.0,88.45,24.37,0.0,8.0,4.0,0.0,False,True,...,False,False,False,False,False,True,False,False,True,True

In [ ]:
# 종속변수에 해당하는 Heart_Disease 컬럼 레이블인코딩 (Yes/No로 되어있음)
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

# Heart_Disease 컬럼 레이블 인코딩
data['Heart_Disease'] = label_encoder.fit_transform(data['Heart_Disease'])

# 결과 확인
data[['Heart_Disease']].head()

# 종속변수에 레이블 인코딩을 하는 이유는 또한 마찬가지로 어떤 클라스에 속하는가가 중요하기 때문에 레이블 인코딩(0, 1, 2, 3, 4 ~)을 하는 것이다.
# 크기를 가져도 학습 과정에 영향을 주지 않기 때문이기도 하다.

   Heart_Disease
0              0
1              1
2              0
3              1
4              0

In [ ]:
help(pd.get_dummies)